version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: survey-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: survey_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - survey-network

  backend:
    build:
      context: ./simple-survey-tool-backend
      dockerfile: Dockerfile
    container_name: survey-backend
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/survey_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - survey-network

  frontend:
    build:
      context: ./simple-survey-tool-frontend
      dockerfile: Dockerfile
    container_name: survey-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge

volumes:
  mariadb_data: